library('data.table')
library('givitiR')
library('ResourceSelection')
library('broom')
setEPS()

# read in probabilities
test <- fread("./probs.19.02.20.csv")
test$STATUS_DISCHARGE<-as.numeric(test$STATUS_DISCHARGE)

# plot
cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$es_i_logistic, devel = "external")
givitiCalibrationTest(test$STATUS_DISCHARGE, e=test$es_i_logistic, devel="external")
postscript("ES1.test.belt.eps")
plot(cb, main = "EuroSCORE1", xlab = "Predicted probability", ylab = "Observed mortality")
dev.off()

cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$es_ii_logistic, devel = "external")
givitiCalibrationTest(test$STATUS_DISCHARGE, e=test$es_ii_logistic, devel="external")
postscript("ES2.test.belt.eps")
plot(cb, main = "EuroSCORE2", xlab = "Predicted probability", ylab = "Observed mortality")
dev.off()

cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$LR, devel = "external")
givitiCalibrationTest(test$STATUS_DISCHARGE, e=test$LR, devel="external")
postscript("LR.test.belt.eps")
plot(cb, main = "LogisticRegression", xlab = "Predicted probability", ylab = "Observed mortality")
dev.off()

cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$RF, devel = "external")
givitiCalibrationTest(test$STATUS_DISCHARGE, e=test$RF, devel="external")
postscript("RF.test.belt.eps")
plot(cb, main = "RandomForest", xlab = "Predicted probability", ylab = "Observed mortality")
dev.off()

cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$NN, devel = "external")
givitiCalibrationTest(test$STATUS_DISCHARGE, e=test$NN, devel="external")
postscript("NN.test.belt.eps")
plot(cb, main = "NeuralNetwork", xlab = "Predicted probability", ylab = "Observed mortality")
dev.off()

# plot fig 2
lr_cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$LR, devel = "external")
rf_cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$RF, devel = "external")
nn_cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$NN, devel = "external")
postscript("Figure 2.eps", height=6, width=18)
par(mfrow=c(1,3))
plot(lr_cb, main = "LogisticRegression", xlab = "Predicted probability", ylab = "Observed mortality", asp=1)
mtext("A", side = 3, cex=1.5, adj = 0, line = 1)
plot(nn_cb, main = "NeuralNetwork", xlab = "Predicted probability", ylab = "Observed mortality", asp=1)
mtext("B", side = 3, cex=1.5, adj = 0, line = 1)
plot(rf_cb, main = "RandomForest", xlab = "Predicted probability", ylab = "Observed mortality", asp=1)
mtext("C", side = 3, cex=1.5, adj = 0, line = 1)
dev.off()

# plot fig 3
es1_cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$es_i_logistic, devel = "external")
es2_cb <- givitiCalibrationBelt(o=test$STATUS_DISCHARGE, e=test$es_ii_logistic, devel = "external")
postscript("Figure 3.eps", height=6, width=12)
par(mfrow=c(1,2))
plot(es1_cb, main = "EuroSCORE1", xlab = "Predicted probability", ylab = "Observed mortality", asp=1)
mtext("A", side = 3, cex=1.5, adj = 0, line = 1)
plot(es2_cb, main = "EuroSCORE2", xlab = "Predicted probability", ylab = "Observed mortality", asp=1)
mtext("B", side = 3, cex=1.5, adj = 0, line = 1)
dev.off()